services:
    admin:
        image: aliasvault-admin
        build:
            context: .
            dockerfile: src/AliasVault.Admin/Dockerfile
        ports:
            - "4431:4431"
        volumes:
            - ./certificates/app:/certificates:rw
            - ./certificates/ssl/admin:/app/ssl:rw
            - ./database:/database:rw
            - ./logs:/logs:rw
        restart: always
        env_file:
            - .env

    client:
        image: aliasvault-client
        build:
            context: .
            dockerfile: src/AliasVault.Client/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certificates/ssl/client:/etc/nginx/ssl:rw
        restart: always
        env_file:
            - .env

    api:
        image: aliasvault-api
        build:
            context: .
            dockerfile: src/AliasVault.Api/Dockerfile
        ports:
            - "4430:4430"
        volumes:
            - ./certificates/app:/certificates:rw
            - ./certificates/ssl/api:/app/ssl:rw
            - ./database:/database:rw
            - ./logs:/logs:rw
        env_file:
            - .env
        restart: always

    smtp:
        image: aliasvault-smtp
        build:
            context: .
            dockerfile: src/Services/AliasVault.SmtpService/Dockerfile
        ports:
            - "25:25"
            - "587:587"
        volumes:
            - ./database:/database:rw
            - ./logs:/logs:rw
        env_file:
            - .env
        restart: always
