services:
    admin:
        image: aliasvault-admin
        build:
            context: .
            dockerfile: src/AliasVault.Admin/Dockerfile
        ports:
            - "8080:8082"
        volumes:
            - ./database:/database
        restart: always
        env_file:
            - .env
    client:
        image: aliasvault-client
        build:
            context: .
            dockerfile: src/AliasVault.Client/Dockerfile
        ports:
            - "80:8080"
        restart: always
        environment:
            - API_URL=http://localhost:81

    api:
        image: aliasvault-api
        build:
            context: .
            dockerfile: src/AliasVault.Api/Dockerfile
        ports:
            - "81:8081"
        volumes:
            - ./database:/database
        env_file:
            - .env
        restart: always

    smtp:
        image: aliasvault-smtp
        build:
            context: .
            dockerfile: src/Services/AliasVault.SmtpService/Dockerfile
        ports:
            - "25:25"
            - "587:587"
        volumes:
            - ./database:/database
        env_file:
            - .env
        restart: always
