services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certificates/ssl:/etc/nginx/ssl:rw
        depends_on:
            - admin
            - client
            - api
            - smtp
        restart: always

    client:
        image: aliasvault-client
        build:
            context: .
            dockerfile: src/AliasVault.Client/Dockerfile
        volumes:
            - ./logs/msbuild:/app/msbuild-logs:rw
        expose:
            - "3000"
        restart: always
        env_file:
            - .env

    api:
        image: aliasvault-api
        build:
            context: .
            dockerfile: src/AliasVault.Api/Dockerfile
        expose:
            - "3001"
        volumes:
            - ./database:/database:rw
            - ./certificates/app:/certificates:rw
            - ./logs:/logs:rw
        env_file:
            - .env
        restart: always

    admin:
        image: aliasvault-admin
        build:
            context: .
            dockerfile: src/AliasVault.Admin/Dockerfile
        expose:
            - "3002"
        volumes:
            - ./database:/database:rw
            - ./certificates/app:/certificates:rw
            - ./logs:/logs:rw
        restart: always
        env_file:
            - .env

    smtp:
        image: aliasvault-smtp
        build:
            context: .
            dockerfile: src/Services/AliasVault.SmtpService/Dockerfile
        ports:
            - "25:25"
            - "587:587"
        volumes:
            - ./database:/database:rw
            - ./logs:/logs:rw
        env_file:
            - .env
        restart: always
