services:
    reverse-proxy:
        image: ghcr.io/lanedirt/aliasvault-reverse-proxy:latest
        ports:
            - "${HTTP_PORT:-80}:80"
            - "${HTTPS_PORT:-443}:443"
        volumes:
            - ./certificates/ssl:/etc/nginx/ssl:rw
            - ./certificates/letsencrypt:/etc/nginx/ssl-letsencrypt:rw
            - ./certificates/letsencrypt/www:/var/www/certbot:rw
        depends_on:
            - admin
            - client
            - api
            - smtp
        restart: always
        env_file:
            - .env

    client:
        image: ghcr.io/lanedirt/aliasvault-client:latest
        volumes:
            - ./logs/msbuild:/src/msbuild-logs:rw
        expose:
            - "3000"
        restart: always
        env_file:
            - .env

    api:
        image: ghcr.io/lanedirt/aliasvault-api:latest
        expose:
            - "3001"
        volumes:
            - ./database:/database:rw
            - ./certificates/app:/certificates/app:rw
            - ./logs:/logs:rw
        restart: always
        env_file:
            - .env
        depends_on:
            - postgres
        environment:
            ConnectionStrings__AliasServerDbContext: "Host=postgres;Database=aliasvault;Username=aliasvault;Password=${POSTGRES_PASSWORD}"

    admin:
        image: ghcr.io/lanedirt/aliasvault-admin:latest
        expose:
            - "3002"
        volumes:
            - ./database:/database:rw
            - ./certificates/app:/certificates/app:rw
            - ./logs:/logs:rw
        restart: always
        env_file:
            - .env
        depends_on:
            - postgres
        environment:
            ConnectionStrings__AliasServerDbContext: "Host=postgres;Database=aliasvault;Username=aliasvault;Password=${POSTGRES_PASSWORD}"

    smtp:
        image: ghcr.io/lanedirt/aliasvault-smtp:latest
        ports:
            - "${SMTP_PORT:-25}:25"
            - "${SMTP_TLS_PORT:-587}:587"
        volumes:
            - ./database:/database:rw
            - ./logs:/logs:rw
        restart: always
        env_file:
            - .env
        depends_on:
            - postgres
        environment:
            ConnectionStrings__AliasServerDbContext: "Host=postgres;Database=aliasvault;Username=aliasvault;Password=${POSTGRES_PASSWORD}"

    task-runner:
        image: ghcr.io/lanedirt/aliasvault-task-runner:latest
        volumes:
            - ./database:/database:rw
            - ./logs:/logs:rw
        restart: always
        env_file:
            - .env
        depends_on:
            - postgres
        environment:
            ConnectionStrings__AliasServerDbContext: "Host=postgres;Database=aliasvault;Username=aliasvault;Password=${POSTGRES_PASSWORD}"

    postgres:
        image: ghcr.io/lanedirt/aliasvault-postgres:latest
        volumes:
            - ./database:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_DB: aliasvault
            POSTGRES_USER: aliasvault
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: always
