services:
    wasm:
        image: aliasvault
        build:
            context: .
            dockerfile: src/AliasVault.WebApp/Dockerfile
        ports:
            - "80:8080"
        restart: always
        environment:
            - API_URL=http://localhost:81

    api:
        image: aliasvault-api
        build:
            context: .
            dockerfile: src/AliasVault.Api/Dockerfile
        ports:
            - "81:8081"
        volumes:
            - ./database:/database
        env_file:
            - .env
        restart: always
