name: Browser Extension Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  chrome-extension:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: browser-extensions/chrome

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: browser-extensions/chrome/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Run linting
        run: npm run lint

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: aliasvault-chrome-extension-${{ github.event_name == 'release' && github.ref_name || (github.ref_name == 'main' && format('main-{0}', github.sha) || github.sha) }}
          path: browser-extensions/chrome/dist/

  upload-release-assets:
    runs-on: ubuntu-latest
    needs: chrome-extension
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: aliasvault-chrome-extension-${{ github.ref_name }}
          path: browser-extensions/chrome/dist/

      - name: Zip Chrome Extension
        run: |
          cd browser-extensions/chrome/dist
          zip -r ../../../aliasvault-chrome-extension.zip .

      - name: Upload Chrome Extension ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: aliasvault-chrome-extension.zip
          token: ${{ secrets.GITHUB_TOKEN }}
