name: Docker Compose Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:26.0.0
        options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Set permissions and run init.sh
        run: |
          chmod +x init.sh
          ./init.sh
      - name: Set up Docker Compose
        run: |
            # Change the exposed host port of the SmtpService from 25 to 2525 because port 25 is not allowed in GitHub Actions
            sed -i 's/25:25/2525:25/' docker-compose.yml
            docker compose -f docker-compose.yml up -d
      - name: Wait for services to be up
        run: |
            # Wait for a few seconds
            sleep 5
      - name: Test if localhost:80 (WASM app) responds
        run: |
            # Test if the service on localhost:80 responds
            http_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80)
            if [ "$http_code" -ne 200 ]; then
              echo "Service did not respond with 200 OK"
              exit 1
            else
              echo "Service responded with 200 OK"
            fi
      - name: Test if localhost:81 (WebApi) responds
        run: |
            # Test if the service on localhost:81 responds
            http_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:81)
            if [ "$http_code" -ne 200 ]; then
                echo "Service did not respond with expected 200 OK. Check if all DB migrations are applied."
                exit 1
            else
                echo "Service responded with $http_code"
            fi
      - name: Test if localhost:2525 (SmtpService) responds
        run: |
              # Test if the service on localhost:2525 responds
              response=$(curl -s --connect-timeout 5 localhost:2525)
              if [ -z "$response" ]; then
                  echo "SmtpService did not respond on port 2525. Check if the SmtpService service is running."
                  exit 1
              else
                  echo "SmtpService responded on port 2525"
              fi
