# This workflow will test if running the integration tests works.
name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet workload install wasm-tools

    - name: Build
      working-directory: apps/server
      run: dotnet build

    - name: Start dev database
      run: ./install.sh configure-dev-db start

    - name: Run integration tests
      working-directory: apps/server
      run: dotnet test Tests/AliasVault.IntegrationTests --no-build --verbosity normal
