name: .NET E2E Client Tests (Playwright)

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    client-tests:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.304

            - name: Install dependencies
              run: dotnet workload install wasm-tools

            - name: Build
              run: dotnet build

            - name: Ensure browsers are installed
              run: pwsh src/Tests/AliasVault.E2ETests/bin/Debug/net8.0/playwright.ps1 install --with-deps

            - name: Run ClientTests with retry
              uses: nick-fields/retry@v3
              with:
                  timeout_minutes: 60
                  max_attempts: 3
                  command: dotnet test src/Tests/AliasVault.E2ETests --no-build --verbosity normal --filter "Category=ClientTests"

            - name: Upload Test Results
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: client-test-results
                  path: TestResults-Client.xml
