# This workflow will test if running the integration tests works.
name: .NET Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet workload install wasm-tools

    - name: Build
      run: dotnet build

    - name: Start dev database
      run: ./install.sh configure-dev-db start

    - name: Wait for database to be up
      run: |
        # Wait for a few seconds
        sleep 5

    - name: Run integration tests
      run: dotnet test src/Tests/AliasVault.IntegrationTests --no-build --verbosity normal
