name: Mobile App Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-react-native-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile-app

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/mobile-app/package-lock.json

      - name: Build and distribute shared libraries
        run: |
          cd ../../shared
          chmod +x build-and-distribute.sh
          ./build-and-distribute.sh

      - name: Verify shared library distribution
        run: |
          # Check if files exist and were recently modified
          TARGET_DIRS=(
            "utils/shared/identity-generator"
            "utils/shared/password-generator"
          )

          for dir in "${TARGET_DIRS[@]}"; do
            if [ ! -d "$dir" ]; then
              echo "❌ Directory $dir does not exist"
              exit 1
            fi

            # Check for required files
            REQUIRED_FILES=("index.js" "index.mjs" "index.d.ts" "index.js.map" "index.mjs.map")
            for file in "${REQUIRED_FILES[@]}"; do
              if [ ! -f "$dir/$file" ]; then
                echo "❌ Required file $dir/$file does not exist"
                exit 1
              fi
            done

            # Check if files were modified in the last 5 minutes
            find "$dir" -type f -mmin -5 | grep -q . || {
              echo "❌ Files in $dir were not recently modified"
              exit 1
            }
          done

          echo "✅ Shared library distribution verified"

      - name: Install dependencies
        run: npm ci

      - name: Build JS bundle (iOS)
        run: |
          mkdir -p build
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ./build/index.ios.bundle \
            --assets-dest ./build

      - name: Run tests
        run: npm run test

      - name: Run linting
        run: npm run lint
